### PR TITLE
onDevSdk: adapt to current master

### PR DESCRIPTION
**Pull request by markus-codewrangler**
See https://github.com/infopark/scrivito_js/pull/10872

### CODE REVIEW

**Comment by apepper** [comment]
Can you try to create a branch, that does not contain the latest "main" commits? If I'm not mistaken you only added [1d4ece8](https://github.com/Scrivito/scrivito-portal-app/pull/397/commits/1d4ece873f13e2c46bdb2394936b540449f40d81).

**Comment by krishan** [comment]
@markus-codewrangler But "adapt to current SDK master" and "update to latest portal main" should maybe be kept separate? Kind of confusing to do it in a single PR, no?

**Comment by markus-codewrangler** [comment]
ok, i see ✅ 

@apepper please review again

**Review by apepper — APPROVED** [review]
LGTM ([3c99d1a](https://github.com/Scrivito/scrivito-portal-app/pull/397/commits/3c99d1afbedddb3de43061be28f3a08b5639d4e1))

**Pull request merged**
