### PR TITLE
auto column widget

### PR DESCRIPTION
**Pull request by agessler**
https://trello.com/c/kAaE9kDm/73-provide-custom-editor-for-autocolumnwidget

Bildschirmfoto 2024-01-10 um 10 25 22

Bildschirmfoto 2024-01-10 um 10 25 33

### CODE REVIEW

**Comment by apepper** [comment]
Please rebase your branch on the current `main` branch.

**Comment by agessler** [comment]
@apepper Rebase done.

**Comment by apepper** [comment]
Please also enable prettier for `.html` in your editor of choice.

**Comment by apepper** [comment]
Can you also provide an example markup, how a column widget in flexible mode is rendered with two columns, on in shrink and one in stretch mode?

**Comment by apepper** [comment]
Closing for now. We have to pick up this work later on.

**Pull request closed without merging**
