### PR TITLE
Add support for equipment hierarchy

### PR DESCRIPTION
**Pull request by dcsaszar**
Content basics are done, but the changes can be merged independently of publishing.

https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-equipment-hierarchy.scrivito-portal-app.pages.dev/en/equipment?_scrivito_workspace_id=p39a063a58da77ba&_scrivito_display_mode=view

### CODE REVIEW

**Review by apepper — COMMENTED** [review]
FEEDBACK ([248568f](https://github.com/Scrivito/scrivito-portal-app/pull/507/commits/248568fc8224db852b4296da3a01d580eb135347))

Very nice 🚀!

Code looks all good.

Content wise: Could you add a reference from a child object back to the parent object? E.g. on https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-equipment-hierarchy.scrivito-portal-app.pages.dev/en/equipment-details-1e241bae572507e8?service_object_id=01F15317280B4BFDA40FFFAF2914D847 a "Belongs to Lubrication system 3x10l/min" - of cause only if there is a parent item.

**Comment by dcsaszar** [comment]
Added it like this.

Not sure if we need the button (maybe it makes clearer what happens on click) and which parts should be linked (whole card or only button).

I also tried without the background but somehow I like the blue area indicator more b/c it feels like an active navigation item.

image

**Review by apepper — APPROVED** [review]
LGTM ([248568f](https://github.com/Scrivito/scrivito-portal-app/pull/507/commits/248568fc8224db852b4296da3a01d580eb135347))

Very nice 🚀!

**Comment by krishan** [comment]
Very cool, I like it 🤩

**Pull request merged**
